### ISSUE TITLE
Passing Config to Container?

### ISSUE THREAD

**Issue by MattMencel** [brandonweeks/vmware_exporter#10]
OK...sorry for the dumb question...I'm really new to this.

How do I pass my yaml file to the Docker container so it reads the config?

**Comment by cristicalin** [comment]
Just butting in as I'm also looking to use this little exporter.
Some README or Makefile would help but in the mean time here is a short intro:

Building:
```
$ docker build -t vsphere_exporter:latest .
```
You can pass http_proxy, https_proxy if you need to set them using `--build-arg http_proxy` and `--build-arg https_proxy`

Running:
Edit your vsphere_exporter.yml and make sure to set credential appropriately
```
$ docker run -itd -v $PWD/vsphere_exporter.yml:/vsphere_exporter.yml \
  --name vsphere_exporter -p 9155:9155 vsphere_exporter:latest \
  /go/bin/app -config.file /vsphere_exporter.yml
```

Depending on how you run your prometheus you may either run it with a link or declare the host IP or docker0 bridge IP in the config. Here's mine just for this experiment:

```
global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vsphere_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.17.0.1:9155']
```
